name: 'git-rev-parse-action'
description: 'git rev-parse action'
author: 'kyo-ago'

inputs:
  target:
    description: 'cache target entries'
    required: true
  file:
    description: 'temporary hash file'
    required: false
    default: 'git-rev-parse-action.hash'

outputs:
  cache-hit:
    description: '"true" or ""'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - run: |
        echo `
          echo "${{ inputs.target }}" | while read -r line; do
            if [ "$line" != "" ]; then
              git rev-parse HEAD:$line
            fi
          done | tr '\r\n' ' ' | tr '\n' ' '
        ` > ${{ inputs.file }}
      shell: bash
    - name: Check workflow files
      run: |
        bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        ./actionlint -color
      shell: bash
    - id: cache
      uses: actions/cache@v2
      with:
        path: ${{ inputs.file }}
        key: ${{ hashFiles(inputs.file) }}
