name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: random
        run: echo "::set-output name=file::${RANDOM}.hash"
      - run: echo "${RANDOM}" > ${{ steps.random.outputs.file }}

      - uses: ./
        id: not-caching
        with:
          target: ${{ steps.random.outputs.file }}

      - run: echo "hoge" > test.txt
      - uses: ./
        id: caching
        with:
          target: test.txt

#      This is not an automated test as the cache save will fail if the CI fails.
      - id: test
        run: |
          if [ "${{ steps.not-caching.outputs.cache-hit }}" != "true" -a "${{ steps.caching.outputs.cache-hit }}" = "true" ]; then
            echo "::set-output name=result::OK"
            exit;
          fi
          echo "::set-output name=result::NG"

      - run: echo "${{ steps.test.outputs.result }}"
